[phases.setup]
nixPkgs = ["python3", "gcc"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install -r requirements.txt"
]

[phases.start]
cmds = ["gunicorn myproject.wsgi:application --bind 0.0.0.0:$PORT"]
