# Generated by Django 4.2.19 on 2025-02-28 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(unique=True)),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department_name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.TextField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.department')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.TextField(help_text='Full name.', max_length=27)),
                ('salary', models.IntegerField(help_text='Salary.')),
                ('email', models.EmailField(help_text='Email address.', max_length=254)),
                ('phone', models.TextField(help_text='Phone number.', max_length=27)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.position')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to='app.customuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='app.customuser')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='app.customuser')),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(help_text='Start date of leave.')),
                ('end_date', models.DateField(help_text='End date of leave.')),
                ('reason', models.TextField(help_text='Reason for leave.')),
                ('status', models.CharField(choices=[('Kutilmoqda', 'Kutilmoqda'), ('Tasdiqlangan', 'Tasdiqlangan'), ('Rad etilgan', 'Rad etilgan')], default='Kutilmoqda', help_text='Leave request status.', max_length=27)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='app.staff')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(help_text='Expense description.')),
                ('amount', models.IntegerField(help_text='Expense amount.')),
                ('date', models.DateField(help_text='Expense date.')),
                ('status', models.CharField(choices=[('Kutilmoqda', 'Kutilmoqda'), ('Tasdiqlangan', 'Tasdiqlangan'), ('Rad etilgan', 'Rad etilgan')], default='Pending', help_text='Expense status.', max_length=27)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='app.staff')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.TextField(help_text='Document title.')),
                ('file', models.FileField(help_text='Upload document file.', upload_to='documents/')),
                ('description', models.TextField(help_text='Document description.')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='app.staff')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='app.role'),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commentary', models.TextField(help_text='Main commentary.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='app.customuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Accounting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.TextField()),
                ('year', models.IntegerField(help_text='Year.')),
                ('incentive_money', models.IntegerField(default=0, help_text='Incentive money.')),
                ('money_withheld_from_salary', models.IntegerField(default=0, help_text='Money withheld from salary.')),
                ('reason_for_withholding', models.TextField(blank=True, help_text='Reason for withholding.', null=True)),
                ('money_withheld_for_income_tax', models.IntegerField(default=0, help_text='Money withheld for income tax.')),
                ('remaining_amount', models.IntegerField(help_text='Remaining amount.')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_records', to='app.staff')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
