# Generated by Django 4.2.19 on 2025-02-10 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.TextField(unique=True)),
                ('password', models.TextField()),
                ('role', models.TextField()),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commentary', models.TextField(help_text='Asosiy sharh.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.TextField(help_text="To'liq ismi.", max_length=27)),
                ('salary', models.IntegerField(help_text='Maoshi.')),
                ('email', models.EmailField(help_text='Elektron pochta manzili.', max_length=254)),
                ('phone', models.TextField(help_text='Telefon raqami.', max_length=27)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.position')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commentary', models.TextField(help_text='Javob matni.')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='app.announcement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(help_text="Ta'til boshlanish sanasi.")),
                ('end_date', models.DateField(help_text="Ta'til tugash sanasi.")),
                ('reason', models.TextField(help_text="Ta'til sababi.")),
                ('status', models.CharField(choices=[('Pending', 'Kutilmoqda'), ('Approved', 'Tasdiqlangan'), ('Rejected', 'Rad etilgan')], default='Pending', help_text="Ta'til so'rovi holati.", max_length=27)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='app.staff')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(help_text='Fikr-mulohaza matni.')),
                ('response', models.TextField(blank=True, help_text='Javob.', null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='app.staff')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(help_text='Xarajat tavsifi.')),
                ('amount', models.IntegerField(help_text='Xarajat miqdori.')),
                ('date', models.DateField(help_text='Xarajat sanasi.')),
                ('status', models.CharField(choices=[('Kutilmoqda', 'Kutilmoqda'), ('Tasdiqlangan', 'Tasdiqlangan'), ('Rad etilgan', 'Rad etilgan')], default='Pending', help_text='Xarajat holati.', max_length=27)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='app.staff')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.TextField(help_text='Hujjat nomi.')),
                ('file', models.FileField(help_text='Hujjat faylini yuklang.', upload_to='documents/')),
                ('description', models.TextField(help_text='Hujjat tavsifi.')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='app.staff')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text="Bo'lim nomi.")),
                ('manager', models.ForeignKey(blank=True, help_text="Bo'lim boshlig'i.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to='app.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Accounting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.TextField()),
                ('year', models.IntegerField(help_text='Yil.')),
                ('incentive_money', models.IntegerField(default=0, help_text="Rag'batlantirish puli.")),
                ('money_withheld_from_salary', models.IntegerField(default=0, help_text='Maoshdan ushlab qolingan pul.')),
                ('reason_for_withholding', models.TextField(blank=True, help_text='Ushlab qolinish sababi.', null=True)),
                ('money_withheld_for_income_tax', models.IntegerField(default=0, help_text='Soliqqa tortilgan pul.')),
                ('remaining_amount', models.IntegerField(help_text='Qolgan summa.')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_records', to='app.staff')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
