# Generated by Django 4.2.19 on 2025-02-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('Kutilmoqda', 'Kutilmoqda'), ('Tasdiqlangan', 'Tasdiqlangan'), ('Rad etilgan', 'Rad etilgan')], default='Kutilmoqda', help_text="Ta'til so'rovi holati.", max_length=27),
        ),
    ]
